CREATE TABLE usuarios (id INTEGER AUTO_INCREMENT NOT NULL, apellidos VARCHAR(255), biografia LONGTEXT, carrera VARCHAR(255), codechefuser VARCHAR(255), codeforcesuser VARCHAR(255), correo VARCHAR(255), fecha_creacion DATETIME, fecha_modificacion DATETIME, lenguajepeferido VARCHAR(255), nombres VARCHAR(255), password VARCHAR(255), semestre INTEGER, spojuser VARCHAR(255), username VARCHAR(255), uvauser VARCHAR(255), ciudad INTEGER, pais VARCHAR(255), rango INTEGER, universidad INTEGER, PRIMARY KEY (id))
CREATE TABLE ejercicios (id INTEGER AUTO_INCREMENT NOT NULL, alias VARCHAR(255), dificultad INTEGER, fecha_creacion DATETIME, fecha_modificacion DATETIME, juez VARCHAR(255), tema_1 VARCHAR(255), tema_2 VARCHAR(255), tema_3 VARCHAR(255), tema_4 VARCHAR(255), titulo VARCHAR(255), url VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE universidades (id INTEGER AUTO_INCREMENT NOT NULL, acronimo VARCHAR(255), fecha_creacion DATETIME, fecha_modificación DATETIME, logourl VARCHAR(255), nombre VARCHAR(255), ciudad INTEGER, pais VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE temario (ID INTEGER NOT NULL, complejidad_tiempo VARCHAR(255), cpp LONGTEXT, fecha_creacion DATETIME, fecha_modificacion DATETIME, java LONGTEXT, orden INTEGER, py LONGTEXT, suborden INTEGER, supergrupo VARCHAR(255), tema VARCHAR(255), texto LONGTEXT, PRIMARY KEY (ID))
CREATE TABLE cert_estadisticas (id INTEGER AUTO_INCREMENT NOT NULL, apellidos VARCHAR(255), ejercicios_correctos INTEGER, fecha VARCHAR(255), fecha_creacion DATETIME, fecha_modificacion DATETIME, nombres VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE feed (id INTEGER AUTO_INCREMENT NOT NULL, fecha_creacion DATETIME, fecha_modificacion DATETIME, imagenurl VARCHAR(255), informacion VARCHAR(255), titulo VARCHAR(255), usuariocreador INTEGER, PRIMARY KEY (id))
CREATE TABLE visitaspormesanio (id INTEGER AUTO_INCREMENT NOT NULL, abril INTEGER, agosto INTEGER, anio INTEGER, diciembre INTEGER, enero INTEGER, febrero INTEGER, fecha_creacion DATETIME, fecha_modificacion DATETIME, julio INTEGER, junio INTEGER, marzo INTEGER, mayo INTEGER, noviembre INTEGER, octubre INTEGER, septiembre INTEGER, PRIMARY KEY (id))
CREATE TABLE auditoria_acceso (id INTEGER AUTO_INCREMENT NOT NULL, correcto SMALLINT, fecha DATETIME, fecha_creacion DATETIME, fecha_modificacion DATETIME, ip VARCHAR(255), usuario INTEGER, PRIMARY KEY (id))
CREATE TABLE paises (Codigo VARCHAR(255) NOT NULL, fecha_creacion DATETIME, fecha_modificacion DATETIME, Pais VARCHAR(255), PRIMARY KEY (Codigo))
CREATE TABLE rangos (id INTEGER AUTO_INCREMENT NOT NULL, acronimo VARCHAR(255), fecha_creacion DATETIME, fecha_modificacion DATETIME, nombre VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE enviosuva (id INTEGER AUTO_INCREMENT NOT NULL, codigo LONGTEXT, ejercicio VARCHAR(255), fecha_creacion DATETIME, fecha_modificacion DATETIME, submissionid VARCHAR(255), lenguajeid INTEGER, userid INTEGER, PRIMARY KEY (id))
CREATE TABLE juecesonline (id INTEGER AUTO_INCREMENT NOT NULL, acronimo VARCHAR(255), fecha_creacion DATETIME, fecha_modificacion DATETIME, nombre VARCHAR(255), urllogo VARCHAR(255), urlpagina VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE uvaurltoid (id INTEGER AUTO_INCREMENT NOT NULL, fecha_creacion DATETIME, fecha_modificacion DATETIME, problemid VARCHAR(255), problemname VARCHAR(255), urlid VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE lenguajes (id INTEGER AUTO_INCREMENT NOT NULL, extension VARCHAR(255), fecha_creacion DATETIME, fecha_modificacion VARCHAR(255), nombre VARCHAR(255), numerofavoritos INTEGER, urldocs VARCHAR(255), urllogo VARCHAR(255), PRIMARY KEY (id))
CREATE TABLE cert_inscripcion (id INTEGER AUTO_INCREMENT NOT NULL, apellidos VARCHAR(255), fecha DATETIME, fecha_creacion DATETIME, fecha_modificacion DATETIME, nombres VARCHAR(255), institucion INTEGER, PRIMARY KEY (id))
CREATE TABLE ciudades (idCiudades INTEGER AUTO_INCREMENT NOT NULL, Ciudad VARCHAR(255), fecha_creacion DATETIME, fecha_modificacion DATETIME, Paises_Codigo VARCHAR(255), PRIMARY KEY (idCiudades))
CREATE TABLE comentarios (id INTEGER AUTO_INCREMENT NOT NULL, fecha DATETIME, fecha_creacion DATETIME, fecha_modificacion DATETIME, texto LONGTEXT, usuario INTEGER, PRIMARY KEY (id))
ALTER TABLE usuarios ADD CONSTRAINT FK_usuarios_ciudad FOREIGN KEY (ciudad) REFERENCES ciudades (idCiudades)
ALTER TABLE usuarios ADD CONSTRAINT FK_usuarios_rango FOREIGN KEY (rango) REFERENCES rangos (id)
ALTER TABLE usuarios ADD CONSTRAINT FK_usuarios_universidad FOREIGN KEY (universidad) REFERENCES universidades (id)
ALTER TABLE usuarios ADD CONSTRAINT FK_usuarios_pais FOREIGN KEY (pais) REFERENCES paises (Codigo)
ALTER TABLE universidades ADD CONSTRAINT FK_universidades_ciudad FOREIGN KEY (ciudad) REFERENCES ciudades (idCiudades)
ALTER TABLE universidades ADD CONSTRAINT FK_universidades_pais FOREIGN KEY (pais) REFERENCES paises (Codigo)
ALTER TABLE feed ADD CONSTRAINT FK_feed_usuariocreador FOREIGN KEY (usuariocreador) REFERENCES usuarios (id)
ALTER TABLE auditoria_acceso ADD CONSTRAINT FK_auditoria_acceso_usuario FOREIGN KEY (usuario) REFERENCES usuarios (id)
ALTER TABLE enviosuva ADD CONSTRAINT FK_enviosuva_lenguajeid FOREIGN KEY (lenguajeid) REFERENCES lenguajes (id)
ALTER TABLE enviosuva ADD CONSTRAINT FK_enviosuva_userid FOREIGN KEY (userid) REFERENCES usuarios (id)
ALTER TABLE cert_inscripcion ADD CONSTRAINT FK_cert_inscripcion_institucion FOREIGN KEY (institucion) REFERENCES universidades (id)
ALTER TABLE comentarios ADD CONSTRAINT FK_comentarios_usuario FOREIGN KEY (usuario) REFERENCES usuarios (id)
